import { ConfigUtils } from "./ConfigUtils";

export const config: {[key: string]: ConfigUtils.SelectionQuestionSource} = {
  "30004": {
    picture: 20004,
    description: "no zuo ____\n不作死就不会死",
    optionTwo: "no byebye",
    optionFour: "good boy",
    pattern: 2,
    stem: "根据图文提示将句子补充完整。",
    brainCircuit: 2,
    comprehension: 2,
    optionThree: "well done",
    optionOne: "no die",
    vocabulary: 2,
    id: 30004,
    knowledge: 2
  },
  "10049": {
    picture: 10048,
    description: "干妈",
    optionTwo: "hot woman",
    optionFour: "dear mom",
    pattern: 0,
    stem: "选择符合图文含义的英文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "the mummy",
    optionOne: "dry mother",
    vocabulary: 6,
    id: 10049,
    knowledge: 1
  },
  "30002": {
    picture: 20002,
    description: "sky long earth long ____\n天长地久有时尽",
    optionTwo: "have over",
    optionFour: "give end",
    pattern: 2,
    stem: "根据图文提示将句子补充完整。",
    brainCircuit: 2,
    comprehension: 2,
    optionThree: "have time",
    optionOne: "sometimes end",
    vocabulary: 2,
    id: 30002,
    knowledge: 2
  },
  "10000": {
    picture: 10000,
    description: "can go",
    optionTwo: "能揍",
    optionFour: "胡诌",
    pattern: 0,
    stem: "选择符合图文含义的中文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "惯揍",
    optionOne: "行走",
    vocabulary: 6,
    id: 10000,
    knowledge: 1
  },
  "10001": {
    picture: 10000,
    description: "行走",
    optionTwo: "waik",
    optionFour: "chi liu",
    pattern: 0,
    stem: "选择符合图文含义的英文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "hang",
    optionOne: "can go",
    vocabulary: 6,
    id: 10001,
    knowledge: 1
  },
  "10002": {
    picture: 10002,
    description: "bear cat",
    optionTwo: "狗熊",
    optionFour: "能喵",
    pattern: 0,
    stem: "选择符合图文含义的中文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "能猫",
    optionOne: "熊猫",
    vocabulary: 6,
    id: 10002,
    knowledge: 1
  },
  "10003": {
    picture: 10002,
    description: "熊猫",
    optionTwo: "good cat",
    optionFour: "black and white",
    pattern: 0,
    stem: "选择符合图文含义的英文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "dog bear",
    optionOne: "bear cat",
    vocabulary: 6,
    id: 10003,
    knowledge: 1
  },
  "10004": {
    picture: 10004,
    description: "box ball",
    optionTwo: "箱子",
    optionFour: "西瓜",
    pattern: 0,
    stem: "选择符合图文含义的中文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "弹珠",
    optionOne: "篮球",
    vocabulary: 6,
    id: 10004,
    knowledge: 1
  },
  "10005": {
    picture: 10004,
    description: "篮球",
    optionTwo: "lantern",
    optionFour: "three point",
    pattern: 0,
    stem: "选择符合图文含义的英文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "orange ball",
    optionOne: "box ball",
    vocabulary: 6,
    id: 10005,
    knowledge: 1
  },
  "10006": {
    picture: 10006,
    description: "angry ball",
    optionTwo: "怒火",
    optionFour: "气愤",
    pattern: 0,
    stem: "选择符合图文含义的中文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "火球",
    optionOne: "气球",
    vocabulary: 6,
    id: 10006,
    knowledge: 1
  },
  "10007": {
    picture: 10006,
    description: "气球",
    optionTwo: "gas hall",
    optionFour: "fly bird",
    pattern: 0,
    stem: "选择符合图文含义的英文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "football",
    optionOne: "angry ball",
    vocabulary: 6,
    id: 10007,
    knowledge: 1
  },
  "10008": {
    picture: 10008,
    description: "teacher father",
    optionTwo: "教你",
    optionFour: "师母",
    pattern: 0,
    stem: "选择符合图文含义的中文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "坑爹",
    optionOne: "师父",
    vocabulary: 6,
    id: 10008,
    knowledge: 1
  },
  "10009": {
    picture: 10008,
    description: "师父",
    optionTwo: "wet man",
    optionFour: "three man go",
    pattern: 0,
    stem: "选择符合图文含义的英文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "teacher mother",
    optionOne: "teacher father",
    vocabulary: 6,
    id: 10009,
    knowledge: 1
  },
  "10010": {
    picture: 10010,
    description: "talk desk",
    optionTwo: "平台",
    optionFour: "讲课",
    pattern: 0,
    stem: "选择符合图文含义的中文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "说书",
    optionOne: "讲台",
    vocabulary: 6,
    id: 10010,
    knowledge: 1
  },
  "10011": {
    picture: 10010,
    description: "讲台",
    optionTwo: "speak long",
    optionFour: "big desk",
    pattern: 0,
    stem: "选择符合图文含义的英文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "say no",
    optionOne: "talk desk",
    vocabulary: 6,
    id: 10011,
    knowledge: 1
  },
  "10012": {
    picture: 10012,
    description: "face egg",
    optionTwo: "面膜",
    optionFour: "盒蛋",
    pattern: 0,
    stem: "选择符合图文含义的中文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "面容",
    optionOne: "脸蛋",
    vocabulary: 6,
    id: 10012,
    knowledge: 1
  },
  "10013": {
    picture: 10012,
    description: "脸蛋",
    optionTwo: "box egg",
    optionFour: "expensive",
    pattern: 0,
    stem: "选择符合图文含义的英文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "good egg",
    optionOne: "face egg",
    vocabulary: 6,
    id: 10013,
    knowledge: 1
  },
  "10014": {
    picture: 10014,
    description: "egg yellow",
    optionTwo: "咸蛋",
    optionFour: "双黄",
    pattern: 0,
    stem: "选择符合图文含义的中文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "粉末",
    optionOne: "蛋黄",
    vocabulary: 6,
    id: 10014,
    knowledge: 1
  },
  "10015": {
    picture: 10014,
    description: "蛋黄",
    optionTwo: "bad egg",
    optionFour: "yummy egg",
    pattern: 0,
    stem: "选择符合图文含义的英文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "end egg",
    optionOne: "egg yellow",
    vocabulary: 6,
    id: 10015,
    knowledge: 1
  },
  "20000": {
    picture: 20000,
    description: "Far up cold shan stone road xia",
    optionTwo: "山外青山楼外楼",
    optionFour: "远看山有色",
    pattern: 15,
    stem: "选择以下句子的正确翻译",
    brainCircuit: 2,
    comprehension: 4,
    optionThree: "远近高低各不同",
    optionOne: "远上寒山石径斜",
    vocabulary: 5,
    id: 20000,
    knowledge: 4
  },
  "20001": {
    picture: 20001,
    description: "no care three seven two ten one",
    optionTwo: "不论是非善恶",
    optionFour: "不关心那些破事",
    pattern: 15,
    stem: "选择以下句子的正确翻译",
    brainCircuit: 2,
    comprehension: 4,
    optionThree: "不到长城非好汉",
    optionOne: "不管三七二十一",
    vocabulary: 5,
    id: 20001,
    knowledge: 4
  },
  "20002": {
    picture: 20002,
    description: "sky long earth long sometimes end",
    optionTwo: "天接云涛连晓雾",
    optionFour: "天教分付与疏狂",
    pattern: 15,
    stem: "选择以下句子的正确翻译",
    brainCircuit: 2,
    comprehension: 4,
    optionThree: "天姥连天向天横",
    optionOne: "天长地久有时尽",
    vocabulary: 5,
    id: 20002,
    knowledge: 4
  },
  "20003": {
    picture: 20003,
    description: "long wind broke lang can sometimes",
    optionTwo: "天长地久有时尽",
    optionFour: "碧苔深锁长门路",
    pattern: 15,
    stem: "选择以下句子的正确翻译",
    brainCircuit: 2,
    comprehension: 4,
    optionThree: "长信宫中秋月明",
    optionOne: "长风破浪会有时",
    vocabulary: 5,
    id: 20003,
    knowledge: 4
  },
  "20004": {
    picture: 20004,
    description: "no zuo no die",
    optionTwo: "没有作业没有死亡",
    optionFour: "不作妖就好办事",
    pattern: 15,
    stem: "选择以下句子的正确翻译",
    brainCircuit: 2,
    comprehension: 4,
    optionThree: "无事做无屠杀",
    optionOne: "不作死就不会死",
    vocabulary: 5,
    id: 20004,
    knowledge: 4
  },
  "20005": {
    picture: 20005,
    description: "old people west bye yellow he building",
    optionTwo: "河上老人坐古槎",
    optionFour: "旧事莫提大丈夫",
    pattern: 15,
    stem: "选择以下句子的正确翻译",
    brainCircuit: 2,
    comprehension: 4,
    optionThree: "前任西天黄河跳",
    optionOne: "故人西辞黄鹤楼",
    vocabulary: 5,
    id: 20005,
    knowledge: 4
  },
  "20006": {
    picture: 20006,
    description: "smoke flower three moon down yangzhou",
    optionTwo: "烟云幻作神仙字",
    optionFour: "烟花巷陌下扬州",
    pattern: 15,
    stem: "选择以下句子的正确翻译",
    brainCircuit: 2,
    comprehension: 4,
    optionThree: "烟花散尽天如墨",
    optionOne: "烟花三月下扬州",
    vocabulary: 5,
    id: 20006,
    knowledge: 4
  },
  "20007": {
    picture: 20007,
    description: "clean ming time festival rain mark mark",
    optionTwo: "佳节清明桃李笑",
    optionFour: "清明祭扫各纷然",
    pattern: 15,
    stem: "选择以下句子的正确翻译",
    brainCircuit: 2,
    comprehension: 4,
    optionThree: "纷纷净明时节雨",
    optionOne: "清明时节雨纷纷",
    vocabulary: 5,
    id: 20007,
    knowledge: 4
  },
  "20008": {
    picture: 20008,
    description: "can people on road want to cut life",
    optionTwo: "琳瑯触目路人惊",
    optionFour: "会人路上剪命根",
    pattern: 15,
    stem: "选择以下句子的正确翻译",
    brainCircuit: 2,
    comprehension: 4,
    optionThree: "能人上路断绝尘",
    optionOne: "路上行人欲断魂",
    vocabulary: 5,
    id: 20008,
    knowledge: 4
  },
  "20009": {
    picture: 20009,
    description: "grape beautiful wine night light cup",
    optionTwo: "葡萄琵琶马上催",
    optionFour: "葡萄压架水晶寒",
    pattern: 15,
    stem: "选择以下句子的正确翻译",
    brainCircuit: 2,
    comprehension: 4,
    optionThree: "西域葡萄事已非",
    optionOne: "葡萄美酒夜光杯",
    vocabulary: 5,
    id: 20009,
    knowledge: 4
  },
  "20010": {
    picture: 20010,
    description: "how many buildings and desks in smoke rain",
    optionTwo: "多少恨夜梦魂中",
    optionFour: "台楼知多少烟雨",
    pattern: 15,
    stem: "选择以下句子的正确翻译",
    brainCircuit: 2,
    comprehension: 4,
    optionThree: "菖蒲叶叶知多少",
    optionOne: "多少楼台烟雨中",
    vocabulary: 5,
    id: 20010,
    knowledge: 4
  },
  "10027": {
    picture: 10026,
    description: "凉快",
    optionTwo: "sad cool",
    optionFour: "blue fast",
    pattern: 0,
    stem: "选择符合图文含义的英文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "big cool",
    optionOne: "cool fast",
    vocabulary: 6,
    id: 10027,
    knowledge: 1
  },
  "10028": {
    picture: 10028,
    description: "sad cool",
    optionTwo: "允悲",
    optionFour: "伤心",
    pattern: 0,
    stem: "选择符合图文含义的中文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "酷毙",
    optionOne: "悲凉",
    vocabulary: 6,
    id: 10028,
    knowledge: 1
  },
  "10029": {
    picture: 10028,
    description: "悲凉",
    optionTwo: "cool fast",
    optionFour: "kujiji",
    pattern: 0,
    stem: "选择符合图文含义的英文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "not good",
    optionOne: "sad cool",
    vocabulary: 6,
    id: 10029,
    knowledge: 1
  },
  "10030": {
    picture: 10030,
    description: "cool shoes",
    optionTwo: "潮男",
    optionFour: "跑酷",
    pattern: 0,
    stem: "选择符合图文含义的中文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "雨靴",
    optionOne: "凉鞋",
    vocabulary: 6,
    id: 10030,
    knowledge: 1
  },
  "10031": {
    picture: 10030,
    description: "凉鞋",
    optionTwo: "cold blood",
    optionFour: "light cool",
    pattern: 0,
    stem: "选择符合图文含义的英文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "ice wear",
    optionOne: "cool shoes",
    vocabulary: 6,
    id: 10031,
    knowledge: 1
  },
  "10032": {
    picture: 10032,
    description: "cool meaning",
    optionTwo: "酷暑",
    optionFour: "凉被",
    pattern: 0,
    stem: "选择符合图文含义的中文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "凉鞋",
    optionOne: "凉意",
    vocabulary: 6,
    id: 10032,
    knowledge: 1
  },
  "10033": {
    picture: 10032,
    description: "凉意",
    optionTwo: "cold blood",
    optionFour: "cool shoes",
    pattern: 0,
    stem: "选择符合图文含义的英文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "how meaning",
    optionOne: "cool meaning",
    vocabulary: 6,
    id: 10033,
    knowledge: 1
  },
  "10034": {
    picture: 10034,
    description: "lose home",
    optionTwo: "失意",
    optionFour: "失败",
    pattern: 0,
    stem: "选择符合图文含义的英文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "回家",
    optionOne: "败家",
    vocabulary: 6,
    id: 10034,
    knowledge: 1
  },
  "10035": {
    picture: 10034,
    description: "败家",
    optionTwo: "hole family",
    optionFour: "go home",
    pattern: 0,
    stem: "选择符合图文含义的英文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "win home",
    optionOne: "lose home",
    vocabulary: 6,
    id: 10035,
    knowledge: 1
  },
  "10036": {
    picture: 10036,
    description: "walk red",
    optionTwo: "行遍",
    optionFour: "飞红",
    pattern: 0,
    stem: "选择符合图文含义的英文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "打滑",
    optionOne: "走红",
    vocabulary: 6,
    id: 10036,
    knowledge: 1
  },
  "10037": {
    picture: 10036,
    description: "走红",
    optionTwo: "go good",
    optionFour: "walk nice",
    pattern: 0,
    stem: "选择符合图文含义的英文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "go well",
    optionOne: "walk red",
    vocabulary: 6,
    id: 10037,
    knowledge: 1
  },
  "10038": {
    picture: 10038,
    description: "face red",
    optionTwo: "晒伤",
    optionFour: "面子",
    pattern: 0,
    stem: "选择符合图文含义的英文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "网红",
    optionOne: "脸红",
    vocabulary: 6,
    id: 10038,
    knowledge: 1
  },
  "10039": {
    picture: 10038,
    description: "脸红",
    optionTwo: "see nice girl",
    optionFour: "face on Tibet",
    pattern: 0,
    stem: "选择符合图文含义的英文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "red cloud",
    optionOne: "face red",
    vocabulary: 6,
    id: 10039,
    knowledge: 1
  },
  "10040": {
    picture: 10040,
    description: "mouth red",
    optionTwo: "上火",
    optionFour: "唇膏",
    pattern: 0,
    stem: "选择符合图文含义的英文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "网红",
    optionOne: "口红",
    vocabulary: 6,
    id: 10040,
    knowledge: 1
  },
  "10041": {
    picture: 10040,
    description: "口红",
    optionTwo: "yang forest",
    optionFour: "channnel",
    pattern: 0,
    stem: "选择符合图文含义的英文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "paint red",
    optionOne: "mouth red",
    vocabulary: 6,
    id: 10041,
    knowledge: 1
  },
  "10042": {
    picture: 10042,
    description: "watch white",
    optionTwo: "看清",
    optionFour: "空白",
    pattern: 0,
    stem: "选择符合图文含义的英文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "发白",
    optionOne: "表白",
    vocabulary: 6,
    id: 10042,
    knowledge: 1
  },
  "10043": {
    picture: 10042,
    description: "表白",
    optionTwo: "say love",
    optionFour: "give rose",
    pattern: 0,
    stem: "选择符合图文含义的英文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "good man",
    optionOne: "watch white",
    vocabulary: 6,
    id: 10043,
    knowledge: 1
  },
  "10044": {
    picture: 10044,
    description: "watch sister",
    optionTwo: "表哥",
    optionFour: "表嫂",
    pattern: 0,
    stem: "选择符合图文含义的英文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "表弟",
    optionOne: "表妹",
    vocabulary: 6,
    id: 10044,
    knowledge: 1
  },
  "10045": {
    picture: 10044,
    description: "表姐",
    optionTwo: "aunt mother",
    optionFour: "handsome sister",
    pattern: 0,
    stem: "选择符合图文含义的英文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "Jiangxi girls",
    optionOne: "watch sister",
    vocabulary: 6,
    id: 10045,
    knowledge: 1
  },
  "10046": {
    picture: 10046,
    description: "old big",
    optionTwo: "旧交",
    optionFour: "靓仔",
    pattern: 0,
    stem: "选择符合图文含义的英文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "小弟",
    optionOne: "老大",
    vocabulary: 6,
    id: 10046,
    knowledge: 1
  },
  "10047": {
    picture: 10046,
    description: "老大",
    optionTwo: "still brother",
    optionFour: "handsome man",
    pattern: 0,
    stem: "选择符合图文含义的英文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "little brother",
    optionOne: "old big",
    vocabulary: 6,
    id: 10047,
    knowledge: 1
  },
  "10048": {
    picture: 10048,
    description: "dry mother",
    optionTwo: "泼妇",
    optionFour: "奶娘",
    pattern: 0,
    stem: "选择符合图文含义的英文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "酵母",
    optionOne: "干妈",
    vocabulary: 6,
    id: 10048,
    knowledge: 1
  },
  "10016": {
    picture: 10016,
    description: "end egg",
    optionTwo: "下蛋",
    optionFour: "成全",
    pattern: 0,
    stem: "选择符合图文含义的中文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "结束",
    optionOne: "完蛋",
    vocabulary: 6,
    id: 10016,
    knowledge: 1
  },
  "30006": {
    picture: 20006,
    description: "____ three moon down yangzhou\n烟花三月下扬州",
    optionTwo: "rainy day",
    optionFour: "how nice",
    pattern: 2,
    stem: "根据图文提示将句子补充完整。",
    brainCircuit: 2,
    comprehension: 2,
    optionThree: "nice flower",
    optionOne: "smoke flower",
    vocabulary: 2,
    id: 30006,
    knowledge: 2
  },
  "10017": {
    picture: 10016,
    description: "完蛋",
    optionTwo: "play end",
    optionFour: "eat egg",
    pattern: 0,
    stem: "选择符合图文含义的英文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "going die",
    optionOne: "end egg",
    vocabulary: 6,
    id: 10017,
    knowledge: 1
  },
  "30007": {
    picture: 20007,
    description: "clean ming ____ rain mark mark\n清明时节雨纷纷",
    optionTwo: "when life",
    optionFour: "bad dog",
    pattern: 2,
    stem: "根据图文提示将句子补充完整。",
    brainCircuit: 2,
    comprehension: 2,
    optionThree: "real sao",
    optionOne: "time festival",
    vocabulary: 2,
    id: 30007,
    knowledge: 2
  },
  "10018": {
    picture: 10018,
    description: "night rice",
    optionTwo: "夜莺",
    optionFour: "约会",
    pattern: 0,
    stem: "选择符合图文含义的中文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "完蛋",
    optionOne: "晚饭",
    vocabulary: 6,
    id: 10018,
    knowledge: 1
  },
  "30000": {
    picture: 20000,
    description: "Far up cold shan ____ xia.\n远上寒山石径斜。",
    optionTwo: "Cha shao",
    optionFour: "sun flower",
    pattern: 2,
    stem: "根据图文提示将句子补充完整。",
    brainCircuit: 2,
    comprehension: 2,
    optionThree: "mo cha",
    optionOne: "stone road",
    vocabulary: 2,
    id: 30000,
    knowledge: 2
  },
  "30008": {
    picture: 20008,
    description: "road on can people want to ____\n路上行人欲断魂",
    optionTwo: "see monster",
    optionFour: "save you",
    pattern: 2,
    stem: "根据图文提示将句子补充完整。",
    brainCircuit: 2,
    comprehension: 2,
    optionThree: "dog belt",
    optionOne: "cut life",
    vocabulary: 2,
    id: 30008,
    knowledge: 2
  },
  "10019": {
    picture: 10018,
    description: "晚饭",
    optionTwo: "breakfast",
    optionFour: "tonight",
    pattern: 0,
    stem: "选择符合图文含义的英文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "fans",
    optionOne: "night rice",
    vocabulary: 6,
    id: 10019,
    knowledge: 1
  },
  "30009": {
    picture: 20009,
    description: "grape beautiful wine ____\n葡萄美酒夜光杯",
    optionTwo: "high level cup",
    optionFour: "night out sad",
    pattern: 2,
    stem: "根据图文提示将句子补充完整。",
    brainCircuit: 2,
    comprehension: 2,
    optionThree: "D cup",
    optionOne: "night light cup",
    vocabulary: 2,
    id: 30009,
    knowledge: 2
  },
  "10020": {
    picture: 10020,
    description: "morning rice",
    optionTwo: "晨练",
    optionFour: "稀饭",
    pattern: 0,
    stem: "选择符合图文含义的中文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "早安",
    optionOne: "早饭",
    vocabulary: 6,
    id: 10020,
    knowledge: 1
  },
  "30010": {
    picture: 20010,
    description: "how many buildings and desks in ____\n多少楼台烟雨中",
    optionTwo: "little rainy",
    optionFour: "mengmeng rain",
    pattern: 2,
    stem: "根据图文提示将句子补充完整。",
    brainCircuit: 2,
    comprehension: 2,
    optionThree: "bomb rain",
    optionOne: "smoke rain",
    vocabulary: 2,
    id: 30010,
    knowledge: 2
  },
  "10021": {
    picture: 10020,
    description: "早饭",
    optionTwo: "important rice",
    optionFour: "coffee rice",
    pattern: 0,
    stem: "选择符合图文含义的英文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "milk egg",
    optionOne: "morning rice",
    vocabulary: 6,
    id: 10021,
    knowledge: 1
  },
  "30011": {
    picture: 30011,
    description:
      "you have __ I will give you some __ see see！\n你有种，我要给你点颜色瞧瞧！",
    optionTwo: "son，power",
    optionFour: "woman，man",
    pattern: 2,
    stem: "根据图文提示将句子补充完整。",
    brainCircuit: 2,
    comprehension: 2,
    optionThree: "power，money",
    optionOne: "seed，colour",
    vocabulary: 2,
    id: 30011,
    knowledge: 2
  },
  "10022": {
    picture: 10022,
    description: "ink fish",
    optionTwo: "黑水",
    optionFour: "墨迹",
    pattern: 0,
    stem: "选择符合图文含义的中文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "潮流",
    optionOne: "墨鱼",
    vocabulary: 6,
    id: 10022,
    knowledge: 1
  },
  "10023": {
    picture: 10022,
    description: "墨鱼",
    optionTwo: "black cat",
    optionFour: "red fish",
    pattern: 0,
    stem: "选择符合图文含义的英文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "ink pen",
    optionOne: "ink fish",
    vocabulary: 6,
    id: 10023,
    knowledge: 1
  },
  "30001": {
    picture: 20001,
    description: "____ three seven two ten one \n不管三七二十一",
    optionTwo: "I count",
    optionFour: "the right",
    pattern: 2,
    stem: "根据图文提示将句子补充完整。",
    brainCircuit: 2,
    comprehension: 2,
    optionThree: "good math",
    optionOne: "no care",
    vocabulary: 2,
    id: 30001,
    knowledge: 2
  },
  "10024": {
    picture: 10024,
    description: "long city",
    optionTwo: "长远",
    optionFour: "龙龟",
    pattern: 0,
    stem: "选择符合图文含义的中文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "久远",
    optionOne: "长城",
    vocabulary: 6,
    id: 10024,
    knowledge: 1
  },
  "30005": {
    picture: 20005,
    description: "old people ____ yellow he building\n故人西辞黄鹤楼",
    optionTwo: "no leave",
    optionFour: "system bye",
    pattern: 2,
    stem: "根据图文提示将句子补充完整。",
    brainCircuit: 2,
    comprehension: 2,
    optionThree: "east go",
    optionOne: "west bye",
    vocabulary: 2,
    id: 30005,
    knowledge: 2
  },
  "10025": {
    picture: 10024,
    description: "长城",
    optionTwo: "great city",
    optionFour: "change",
    pattern: 0,
    stem: "选择符合图文含义的英文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "old wall",
    optionOne: "long city",
    vocabulary: 6,
    id: 10025,
    knowledge: 1
  },
  "30003": {
    picture: 20003,
    description: "____ broke lang can sometimes\n长风破浪会有时",
    optionTwo: "big blow",
    optionFour: "big ship",
    pattern: 2,
    stem: "根据图文提示将句子补充完整。",
    brainCircuit: 2,
    comprehension: 2,
    optionThree: "great melon",
    optionOne: "long wind",
    vocabulary: 2,
    id: 30003,
    knowledge: 2
  },
  "10026": {
    picture: 10026,
    description: "cool fast",
    optionTwo: "酷男",
    optionFour: "凉面",
    pattern: 0,
    stem: "选择符合图文含义的中文",
    brainCircuit: 2,
    comprehension: 1,
    optionThree: "飞快",
    optionOne: "凉快",
    vocabulary: 6,
    id: 10026,
    knowledge: 1
  }
};
